name: "pre-release"

on:
  push:
  workflow_dispatch:

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"
    container: devkitpro/devkita64
    steps:
      # ...
      - name: Building Uberhand
        run: |
          make

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          draft: true
          title: "Uberhand"
          files: |
            ovlmenu.ovl