name: Build AIO-switch-updater

on: 
  push:
  workflow_dispatch:

jobs:
  AIO-switch-updater:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64
    steps:
    - uses: actions/checkout@v1
      
    - name: Building Uberhand
      run: |
        make
        
    - uses: actions/upload-artifact@master
      with:
        name: ovlmenu
        path: ovlmenu.ovl