name: "Test Uberhand"

on:
  pull_request:
  workflow_dispatch:

jobs:
  Test-Uberhand:
    name: "Build Test"
    runs-on: "ubuntu-latest"
    container: devkitpro/devkita64
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: make
